
package com.wx.purchaseRecord.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2.8
 * 
 */
@XmlRootElement(name = "FatalException", namespace = "http://service.purchaseRecord.wx.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatalException", namespace = "http://service.purchaseRecord.wx.com/", propOrder = {
    "errorMessage",
    "message"
})
public class FatalExceptionBean {

    private String errorMessage;
    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getErrorMessage() {
        return this.errorMessage;
    }

    /**
     * 
     * @param errorMessage
     *     the value for the errorMessage property
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
